site: #!include flatirons_site.yaml
  data:
    lat: 27.18077
    lon: -96.933
    elev: 0
    year: 2013
    site_boundaries: # Not used in offshore simulation. Site determined using orbit.
      verts:  
        - [0.0, 0.0]
        - [0.0, 2000.0]
        - [2000.0, 2000.0]
        - [2000.0, 0.0] 
      verts_simple: 
        - [0.0, 0.0]
        - [0.0, 2000.0]
        - [2000.0, 2000.0]
        - [2000.0, 0.0]
  solar_resource_file: "input/weather/solar/27.609619705160302_-97.40229985722155_27.7372_-97.5426_psm3_60_2013.csv" # Solar location is onshore
  wind_resource_file: "input/weather/wind/27.18077_-96.933_windtoolkit_2013_60min_160m_200m.srw"
  wave_resource_file: ""
  grid_resource_file: ""
  hub_height: 168.0
  capacity_hours: []
  solar: true
  wind: true
  wave: false
  wind_resource_origin: "WTK"
  
technologies:
  wind:
    num_turbines: 58
    turbine_rating_kw: 17000.0
    model_name: floris
    timestep: [0, 8760]
    floris_config: input_files/floris/floris_input_osw_17MW.yaml
    fin_model: !include default_fin_config.yaml
  pv:
    system_capacity_kw: 1000
    dc_degradation: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    fin_model: !include default_fin_config.yaml
  battery:
    system_capacity_kwh: 100000
    system_capacity_kw: 100000
    minimum_SOC: 20.0
    maximum_SOC: 100.0
    initial_SOC: 90.0
    fin_model: !include default_fin_config.yaml
  grid:
    interconnect_kw: 2229000
    fin_model: !include default_fin_config.yaml

config:
  simulation_options:
    wind:
      skip_financial: true
  dispatch_options:
    battery_dispatch: load_following_heuristic # load_following_heuristic #heuristic
    solver: cbc
    n_look_ahead_periods: 48
    grid_charging: false
    pv_charging_only: false
    include_lifecycle_count: false
  cost_info: # Costs from GS Manuscript Supplemental Table S11
    # wind_installed_cost_mw: 3526000 # based on 2023 ATB moderate case for offshore wind
    solar_installed_cost_mw: 991000 # (2020USD) 
    storage_installed_cost_mwh: 158000 # (2020USD) 
    storage_installed_cost_mw: 212000 # (2020USD) 
    # wind_om_per_kw: 104.271
    pv_om_per_kw:  17.2 # (2020USD) 
    battery_om_per_kw: 9.25 # (2020USD) based on 0.025 percent of battery capex with a 100MW 1hr battery
